---
  version: "3"
  services:
    lewagon:
      image: runfire9/lw-bootcamp:latest
      container_name: lewagon
      network_mode: host
      volumes:
        - ${LW_HOME_PATH}:/home/wagon
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - ${SSH_PK_PATH}:/home/wagon/.ssh/id.pk:ro
      restart: on-failure
      command: ["sleep","infinity"]

    lewagon-postgres:
      image: postgres:12-alpine
      container_name: lewagon-postgres
      environment:
        - POSTGRES_PASSWORD=${LW_POSTGRES_ROOT_PASSWORD}
        - USER=wagon
      network_mode: host
      restart: on-failure
      volumes:
        - ${LW_DATABASE_PATH}:/var/lib/postgresql/data/
        - ./init-database-user.sh:/docker-entrypoint-initdb.d/init-database-user.sh

